ktor:
  application:
    modules:
      - top.yunp.aog.ApplicationKt.module
  deployment:
    port: 8080


aog:
  web:
    static: src/main/as3/static
    templates: src/main/as3/templates
    ws_base: /ws
  entrypoint:
    file: src/main/as3/bin/js-release/Main.js
    class: Main