ktor:
  application:
    modules:
      - top.yunp.aog.ApplicationKt.module
  deployment:
    port: 8080


aog:
  static:
    root_dir: src/main/as3/static
  websocket:
    base: /ws
  entrypoint:
    file: src/main/as3/bin/js-release/Main.js
    class: Main